steps:

- name: 'bash'
  id: provide service account key
  script: |
    echo about to provide service-account key.
    echo $SERVICE_ACCOUNT_KEY_JSON > sa_key.json
    echo created key file.
    echo GOOGLE_APPLICATION_CREDENTIALS=sa_key.json > .env
    echo created env file.
    echo key file:
    cat sa_key.json | grep project_id
    echo env file:
    cat .env
    echo done! successfully provided service-account key.
  secretEnv: ['SERVICE_ACCOUNT_KEY_JSON']

- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$BRANCH_NAME:$SHORT_SHA', '.']

serviceAccount: '$SERVICE_ACCOUNT'
options:
  logging: CLOUD_LOGGING_ONLY
  automapSubstitutions: true
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/g51-build-sa-key/versions/1
    env: 'SERVICE_ACCOUNT_KEY_JSON'
  # - versionName: projects/$PROJECT_ID/secrets/somekey/versions/1
  #   env: 'SERVICE_ACCOUNT_KEY_JSON'
