steps:
- name: 'docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/$BRANCH_NAME:$SHORT_SHA', '.']
serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/garage51-nextjs-prod-sa@garage51.iam.gserviceaccount.com'