steps:

- name: 'bash'
  id: provide service account key
  script: |
    echo $SERVICE_ACCOUNT_KEY_JSON > /workspace/sa_key.json
    echo created key file.
    # echo GOOGLE_APPLICATION_CREDENTIALS=/workspace/sa_key.json > /workspace/.env
    # echo created env file.
    echo done! successfully provided service-account key.
  secretEnv: ['SERVICE_ACCOUNT_KEY_JSON']

- name: 'docker'
  args: ['build', '--platform linux/amd64', '-t', 'gcr.io/$PROJECT_ID/$BRANCH_NAME:$SHORT_SHA', '.']

  # https://cloud.google.com/build/docs/configuring-builds/pass-data-between-steps

serviceAccount: '$SERVICE_ACCOUNT'
options:
  logging: CLOUD_LOGGING_ONLY
  automapSubstitutions: true
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/g51-build-sa-key/versions/1
    env: 'SERVICE_ACCOUNT_KEY_JSON'
  # - versionName: projects/$PROJECT_ID/secrets/somekey/versions/1
  #   env: 'SERVICE_ACCOUNT_KEY_JSON'
